'use strict';
const $=s=>document.querySelector(s);
const escapeHTML=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
var deals=[];
const menu=$('.menu');
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));$('#navigation').classList.toggle('open',open)});
$('#navigation').addEventListener('click',e=>{if(e.target.closest('a')){menu.setAttribute('aria-expanded','false');$('#navigation').classList.remove('open')}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){menu.setAttribute('aria-expanded','false');$('#navigation').classList.remove('open')}});
function render(filter='all'){
$('#featured').innerHTML='';
if(filter==='inspiration'){renderInspiration();return;}
const list=deals.filter(d=>filter==='all'||(filter==='cruise'?d.tag==='קרוז':d.tag!=='קרוז'));
const feature=list[0];
if(feature){$('#featured').innerHTML=`<article class="featured"><img src="${escapeHTML(feature.image)}" alt="${escapeHTML(feature.imageAlt)}"><div class="featured-content"><span class="tag">מסע נבחר מהאתר</span><h3>${escapeHTML(feature.title)}</h3><p>${escapeHTML(feature.cardDesc)}</p><div class="facts"><span>${escapeHTML(feature.meta)}</span><span><bdi>${escapeHTML(feature.dates)}</bdi></span><span>החל מ־<br><strong><bdi>${escapeHTML(feature.price)}</bdi></strong><br>${escapeHTML(feature.priceNote)}</span></div><button class="details" data-deal="${escapeHTML(feature.id)}">לפרטים והצעה מותאמת אישית ←</button></div></article>`;}
$('#packages-grid').innerHTML=list.slice(1).map(d=>`<article class="card"><div class="card-media"><img src="${escapeHTML(d.image)}" alt="${escapeHTML(d.imageAlt)}" loading="lazy"><span class="tag">${escapeHTML(d.tag)}</span></div><div class="card-body"><p class="meta">${escapeHTML(d.meta)} · <bdi>${escapeHTML(d.dates)}</bdi></p><h3>${escapeHTML(d.title)}</h3><p class="card-desc">${escapeHTML(d.cardDesc)}</p><div class="card-bottom"><div><span class="price-label">החל מ־</span><bdi class="price">${escapeHTML(d.price)}</bdi><span class="price-label">${escapeHTML(d.priceNote)} · בכפוף לאימות</span></div><button class="details" data-deal="${escapeHTML(d.id)}" aria-label="פרטים על ${escapeHTML(d.title)}">לפרטי המסע ←</button></div></div></article>`).join('');
}
fetch('data/deals.json',{cache:'no-store'}).catch(()=>fetch('https://raw.githubusercontent.com/ifamorovitz-hue/moroshabat/main/data/deals.json?t='+Date.now(),{cache:'no-store'})).then(r=>{if(!r.ok)throw Error('load');return r.json()}).then(data=>{deals=data.filter(d=>d.active!==false).sort((a,b)=>(a.order||0)-(b.order||0));render()}).catch(()=>{$('#packages-grid').innerHTML='<p>לא ניתן לטעון את החבילות. אפשר <a href="#contact">לפנות ליפעת לתכנון אישי</a>.</p>'});
$('.filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});render(b.dataset.filter)});
const dialog=$('#deal-dialog');
$('.packages').addEventListener('click',e=>{const b=e.target.closest('[data-deal]');if(!b)return;const d=deals.find(d=>d.id===b.dataset.deal);const list=v=>'<ul>'+v.map(x=>'<li>'+escapeHTML(x)+'</li>').join('')+'</ul>';$('#deal-content').innerHTML=`<img src="${escapeHTML(d.image)}" alt="${escapeHTML(d.imageAlt)}"><div class="dialog-body"><p class="eyebrow">${escapeHTML(d.tag)}</p><h2 id="deal-title">${escapeHTML(d.title)}</h2><p class="meta">${escapeHTML(d.meta)} · <bdi>${escapeHTML(d.dates)}</bdi></p><p>${escapeHTML(d.desc)}</p>${d.itinerary?list(d.itinerary.map(x=>x.day+' — '+x.text)):''}${d.route?list(d.route):''}${d.facts?list(d.facts):''}${d.priceTiers?list(d.priceTiers):''}<p class="fine">${escapeHTML(d.note)}</p><p class="fine">פרטי החבילה מהאתר הקיים. תאריכים, מחירים וזמינות דורשים אימות עם יפעת.</p><button class="button" id="choose-deal">בואו נדבר על החופשה הזו ←</button></div>`;dialog.showModal();$('#choose-deal').addEventListener('click',()=>{$('[name="destination"]').value=d.title;dialog.close();$('#contact').scrollIntoView();$('[name="destination"]').focus({preventScroll:true})})});
$('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
$('#vacation-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);const rows=['היי יפעת! אשמח לתכנן חופשה יחד.'];[['fullName','שם'],['phone','טלפון'],['destination','יעד'],['type','סוג החופשה'],['travelers','נוסעים'],['dates','מתי'],['duration','משך החופשה'],['style','סגנון'],['budget','תקציב משוער'],['notes','עוד קצת על החופשה']].forEach(([key,label])=>{const value=String(f.get(key)||'').trim();if(value)rows.push(label+': '+value)});const url='https://wa.me/972528403104?text='+encodeURIComponent(rows.join('\n'));window.open(url,'_blank','noopener,noreferrer');const status=$('#form-status');status.textContent='ההודעה מוכנה. השלימו את השליחה בוואטסאפ. ';const fallback=document.createElement('a');fallback.href=url;fallback.target='_blank';fallback.rel='noopener';fallback.textContent='אם לא נפתח, לחצו כאן';fallback.className='text-link';status.append(fallback)});

function renderInspiration(){
const options=[['תאילנד — פוקט וקופיפי',1158,554,345,166],['ניו יורק',785,554,344,166],['מלדיביים',421,554,335,166],['יפן — מסע בין מסורת לטכנולוגיה',33,554,358,166]];
$('#packages-grid').innerHTML=options.map(([name,x,y,w,h])=>`<article class="card"><div class="photo" role="img" aria-label="${name} — תמונת השראה מההדמיה" style="aspect-ratio:${w}/${h}"><img src="assets/5.png" alt="" style="width:${1536/w*100}%;max-width:none;left:${-x/w*100}%;top:${-y/h*100}%"></div><div class="card-body"><h3>${name}</h3><p class="inspiration-label">יעד להשראה מתוך ההדמיה · ללא חבילה או מחיר מאומתים</p><button class="details inspiration" data-destination="${name}">לתכנון אישי ←</button></div></article>`).join('');
}
$('.packages').addEventListener('click',e=>{const b=e.target.closest('[data-destination]');if(!b)return;$('[name="destination"]').value=b.dataset.destination;$('#contact').scrollIntoView();$('[name="destination"]').focus({preventScroll:true})});
